config/routes.rb
Rails.application.routes.draw do
  devise_for :users, skip: [:confirmations, :mailer, :passwords, :unlocks], controllers: {
    registrations: 'users/registrations',
  }
  root to:'home#index'
  get "/rooms/own/:id", to: "rooms#own"
  get "/reservations/confirm", to: "reservations#confirm"
  resources :rooms, only:[:index, :new, :create, :show]
  resources :reservations, only:[:index, :create]
  resources :users, only:[:show, :edit]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reservation.rb
class Reservation < ApplicationRecord
    validates :checkin, presence: true
    validates :checkout, presence: true
    validates :people, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
    validate :date_check

    belongs_to :user
    belongs_to :room
    
    def date_check
        if not(self.checkin.blank? && self.checkout.blank?) && self.checkin < Date.today
            errors.add(:checkin, "は、明日以降の日付を指定して下さい")
        elsif not(self.checkin.blank? && self.checkout.blank?) && self.checkout <= self.checkin
            errors.add(:checkout, "は、チェックイン日の翌日以降の日付を指定して下さい")
        end
    end
end

app/models/room.rb
class Room < ApplicationRecord    
    validates :name, presence: true
    validates :detail, presence: true
    validates :fee, presence: true, numericality: {only_integer: true, greater_than_or_equal_to: 1}
    validates :address, presence: true

    belongs_to :user
    has_many :reservations
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attr_accessor :current_password
  validates :name, presence: true

  has_many :rooms
  has_many :reservations

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :index, :confirm]

  def index
    @reservations = Reservation.where(user_id:params[:id])
  end

  def create
    @reservation = Reservation.new(params.require(:reservation).permit(:checkin, :checkout, :people, :user_id, :room_id))
    if @reservation.save
      flash[:notice] = "予約が完了しました"
      redirect_to reservations: index,  params:{"id" => current_user.id}
    else
      render "rooms/show", locals: {id: @reservation.room_id}
    end
  end

  def confirm
    @reservation = Reservation.new(params.require(:reservation).permit(:checkin, :checkout, :people, :user_id, :room_id))
    @room = @reservation.room
    unless @reservation.valid?
      flash.now[:alert] = "予約情報に不備があります"
      render "rooms/show", locals: {id: @reservation.room_id}
    end
  end  
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!, only: [:create, :new, :show, :own]

  def index
    case params[:search]
    when "1" #住所で検索
      @rooms = Room.where("address LIKE?", "#{params[:address]}")
    when "2" #あいまい検索  
      @rooms = Room.merge(Room.where("address LIKE?", "%#{params[:address]}%"))
                    .merge(Room.where("name LIKE?", "%#{params[:keyword]}%").or(Room.where("detail LIKE?", "%#{params[:keyword]}%")))
    end
  end

  def create
    @room = Room.new(params.require(:room).permit(:name, :icon, :introduce, :fee, :area, :address, :detail))
    @room.user_id= current_user.id
    @room.icon = "/default_hotel_image.png"
    if @room.save
      if params[:room][:icon]
        image = params[:room][:icon].tempfile.read
        File.binwrite("public/room_images/#{@room.id}.png", image)
        @room.icon = "/room_images/#{@room.id}.png" 
        @room.save     
      end
      flash[:notice] = "登録が完了しました"
      redirect_to "/rooms/own/#{current_user.id}"
    else
      flash.now[:alert] = "登録に失敗しました"
      render "new"
    end   
  end

  def new
    @room = Room.new()
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new()
  end

  def own
    @rooms = Room.where(user_id: params[:id])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  def edit
    @section = params[:section]
    @path = "/users/edit?section=#{@section}"
    super
  end

  # PUT /resource
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    
    resource_updated = update_resource(resource, account_update_params)
    yield resource if block_given?
    if resource_updated
      flash[:notice] = "ユーザー情報が更新されました"
      bypass_sign_in resource, scope: resource_name if sign_in_after_change_password?
      redirect_to user_url(id:current_user.id, section:"account")
    else
      flash.now[:alert] = "入力内容に不備があります"
      clean_up_passwords resource
      set_minimum_password_length
      respond_with resource, locals: {section: params[:section]}
    end
  end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :icon])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :introduce, :icon, :section])
  end

  def update_resource(resource, params)
    if params[:password].blank? && params[:password_confirmation].blank?
      if params[:icon]
        image = params[:icon].tempfile.read
        File.binwrite("public/icon_images/#{current_user.id}.png", image)
        params[:icon] = "/icon_images/#{current_user.id}.png"
      end
      resource.update_without_password(params)
    else
      resource.update_with_password(params)
    end
  end

  # The path used after sign up.
  def after_update_path_for(resource)
    user_path(id:current_user.id, section:"account")
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:show]

  def show
    @user= User.find(params[:id])
    @section = params[:section]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="first-view">
    <div class="container">
        <h1>Potepan Shareで<br>
            まだ体験したことのない<br>
            旅をしよう</h1>
        <div class="area-search">
            <div class="search-wrapper">
                <%= form_with(url:rooms_path, method: :get) do |f| %>
                    <div class="field">
                        <%= f.text_field :address, autofocus: true, placeholder: "エリア名を入力" %>
                    </div>
                    <%= f.hidden_field :search, value: "1" %>
                    <div class="actions">
                        <%= f.submit "検索" %>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <div class="recommend">
        <p>おすすめのエリア</p>
        <div class="areas">
            <%= link_to render("shared/area",  pic:"Tokyo.jpg", p1:"東京", p2:"Tokyo"), rooms_path(search: 1, address: "%東京%") %>
            <%= link_to render("shared/area",  pic:"Osaka.jpg", p1:"大阪", p2:"Osaka"), rooms_path(search: 1, address: "%大阪%") %>
            <%= link_to render("shared/area",  pic:"Kyoto.jpg", p1:"京都", p2:"Kyoto"), rooms_path(search: 1, address: "京都%") %>
            <%= link_to render("shared/area",  pic:"Sapporo.jpg", p1:"札幌", p2:"Sapporo"), rooms_path(search: 1, address: "%札幌%") %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railstest2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header" %>

    <!-- <p class="notice"><%= notice %></p> -->
    <!-- <p class="alert"><%= alert %></p> -->

    <%= yield %>

    <%= render "shared/footer" %>
    
  </body>
</html>

app/views/reservations/confirm.html.erb
<div class="container">
    <h3>予約内容の確認</h3>
    <div class="confirm-wrapper">
        <table class="table-type1">
            <tr>
                <th>チェックイン</th>
                <td><%= @reservation.checkin %></td>
            </tr>
            <tr>
                <th>チェックアウト</th>
                <td><%= @reservation.checkout %></td>
            </tr>
            <tr>
                <th>日数</th>
                <td><%= (@reservation.checkout - @reservation.checkin).to_i %>日</td>
            </tr>
            <tr>
                <th>人数</th>
                <td><%= @reservation.people %>人</td>
            </tr>
            <tr>
                <th>お支払い金額</th>
                <td>¥ <%= ((@reservation.checkout - @reservation.checkin) * @reservation.people * @reservation.room.fee).to_i %></td>
            </tr>
        </table>
        <p>上記内容でよろしければ「確定」ボタンを押して下さい</p>
        <div class="confirm-button">
            <%= link_to "予約を確定する", reservations_url(reservation:{checkin: @reservation.checkin, checkout: @reservation.checkout, people: @reservation.people, user_id: @reservation.user_id, room_id: @reservation.room_id}), method: :post %>
            <%= link_to "戻る", :back %>
        </div>
    </div>
</div>

app/views/reservations/index.html.erb
<div class="container">
    <h3>予約済み一覧</h3>
    <table class="table-type2">
        <tr>
            <th>画像</th>
            <th>施設名</th>
            <th class="detail">紹介文</th>
            <th>合計料金</th>
            <th>チェックイン</th>
            <th>チェックアウト</th>
            <th>予約確定日時</th>
            <th></th>
        </tr>
        <% @reservations.each do |reservation| %>
            <tr>
                <td><%= image_tag reservation.room.icon %></td>
                <td><%= link_to reservation.room.name, reservation.room %></td>
                <td><%= reservation.room.detail %></td>
                <td>¥ <%= reservation.room.fee * reservation.people * (reservation.checkout - reservation.checkin).to_i %></td>
                <td><%= l reservation.checkin, format: :short %></td>
                <td><%= l reservation.checkout, format: :short %></td>
                <td><%= l reservation.created_at, format: :default %></td>
                <td></td>
            </tr>
        <% end %>
    </table>
</div>

app/views/rooms/index.html.erb
<%= render "shared/search" %>
<div class="container">
    <% if @rooms %>
        <p><%= @rooms.count %>件が見つかりました</p>
        <div class="rooms-wrapper">
            <% @rooms.each do |room| %>
                <%= render "shared/room",obj: room %>
            <% end %>
        </div>
    <% else %>
        <p>施設が登録されていません</p>
        <%= link_to "施設の新規登録", new_room_path %>
    <% end %>
</div>

app/views/rooms/new.html.erb
<div class="form-wrapper">
  <div class="container">
    <div class="form">
      <h2>施設登録</h2>
      <div class="errors">
        <% if @room.errors.any? %>
            <ul>
              <% @room.errors.full_messages.each do |error| %>
                  <li><%= error %></li>
              <% end %>
            </ul>
        <% end %>
      </div>
      <%= form_with model:@room, local: true do |f| %>

        <div class="field">
          <%= f.label :name %><br />
          <%= f.text_field :name, autofocus: true, autocomplete: "施設名" %>
        </div>

        <div class="field">
          <%= f.label :detail %><br />
          <%= f.text_area :detail, autofocus: true, autocomplete: "施設詳細" %>
        </div>

        <div class="field">
          <%= f.label :fee %><br />
          <%= f.text_field :fee, autocomplete: "料金" %>
        </div>

        <div class="field">
          <%= f.label :address %><br />
          <%= f.text_field :address, autocomplete: "住所" %>
        </div>

        <div class="field image">
          <%= f.label :icon %><br />
          <%= f.file_field :icon, autocomplete: "施設画像" %>
        </div>

        <div class="actions">
          <%= f.submit "保存" %>
        </div>
      <% end %>

      <%= link_to "キャンセル", :back %>
    </div>
  </div>
</div>

app/views/rooms/own.html.erb
<div class="container">
    <h3 class="reservation">登録済み一覧</h3>
    <table class="table-type2">
        <tr>
            <th>画像</th>
            <th>施設名</th>
            <th class="detail">紹介文</th>
            <th>料金</th>
            <th>作成日</th>
            <th></th>
        </tr>
        <% @rooms.each do |room| %>
            <tr>
                <td><%= image_tag room.icon %></td>
                <td><%= link_to room.name, room %></td>
                <td><%= room.detail %></td>
                <td>¥ <%= room.fee %>〜</td>
                <td><%= l room.created_at, format: :short %></td>
                <td></td>
            </tr>
        <% end %>
    </table>
</div>

app/views/rooms/show.html.erb
<%= render "shared/search" %>
<div class="container">
    <%= link_to "← 戻る", :back, class: "back-button"%>
    <div class="detail-wrapper">
        <div class= "room-icon">
            <%= image_tag @room.icon %>
        </div>
        <div class="detail2">
            <div class="detail3 room">
                <div class="room-detail-wrapper">
                    <h4><%= @room.name %></h4>
                    <p class="address"><%= @room.address %></p>
                </div>
                <p class="fee">¥<%= @room.fee %>〜</p>
            </div>
            <p class="detail"><%= @room.detail %></p>
            <div class="reserve-form">
                <div class="errors">
                    <% if @reservation.errors.any? %>
                        <ul>
                            <% @reservation.errors.full_messages.each do |error| %>
                                <li><%= error %></li>
                            <% end %>
                        </ul>
                    <% end %>
                </div>
                <%= form_with model:@reservation, url:"/reservations/confirm", method: :get do |f| %>
                    <div class="reserve-information">
                        <div class="info-form">
                            <%= f.label Reservation.human_attribute_name(:checkin) %>
                            <%= f.date_field :checkin %>
                        </div>
                        <div class="info-form">
                            <%= f.label Reservation.human_attribute_name(:checkout) %>
                            <%= f.date_field :checkout %>
                        </div>
                        <div class="info-form people">
                            <%= f.label Reservation.human_attribute_name(:people) %>
                            <%= f.text_field :people, placeholder: "0" %>
                        </div>
                        <%= f.hidden_field :user_id, value: current_user.id %>
                        <%= f.hidden_field :room_id, value: @room.id %>
                    </div>
                    <div class="actions">
                        <%= f.submit "予約する" %>
                    </div>
                <%end%>
                </div>
            </div>
        </div> 
    </div>       
    
</div>

app/views/shared/_account.html.erb
<div class="container account-menu">
    <h3>設定</h3>
    <div class="profile-wrapper">
        <div class="profile-menu">
            <table>
                <% if obj1 == :email %>
                    <div>
                        <tr class="orange"><th><%= link_to "アカウント", user_path(section:"account") %></th></tr>
                    </div>
                    <div>
                        <tr><th><%= link_to "プロフィール", user_path(section: "profile") %></th></tr>
                    </div>
                <% else %>
                    <div>
                        <tr><th><%= link_to "アカウント", user_path(section:"account", id:@user.id) %></th></tr>
                    </div>
                    <div>
                        <tr class="orange"><th><%= link_to "プロフィール", user_path(section: "profile", id: @user.id) %></th></tr>
                    </div>
                <% end %>
            </table>
        </div>
        <div class="profile-data">
            <div class="table-name">
                <h3><%= obj0 %></h3>
                <%= link_to "編集", edit_user_registration_url(section: section) %>
            </div>
            <table class="table-type1 user-detail">
                <tr>
                    <th><%= User.human_attribute_name(obj1) %></th>
                    <% if obj1 == :icon %>
                        <td><%= image_tag @user[obj1] %></td>
                    <% else %>
                        <td><%= @user[obj1] %></td>
                    <% end %>
                </tr>
                <tr>
                    <th><%= User.human_attribute_name(obj2) %></th>
                    <% if obj2 == :password %>
                        <td>************</td>
                    <% else %>
                        <td><%= @user[obj2] %></td>
                    <% end %>
                </tr>
                <tr>
                    <% unless obj3 == "" %>
                        <th><%= User.human_attribute_name(obj3) %></th>
                    <% else %>
                        <th></th>
                    <% end %>
                    <td><%= @user[obj3] %></td>
                </tr>
            </table>
        </div>
    </div>
</div>

app/views/shared/_account_edit.html.erb
<div class="container account-menu">
    <h3>設定</h3>
    <div class="profile-wrapper">
        <div class="profile-menu">
            <table>
                <% if obj1 == :email %>
                    <div>
                        <tr class="orange"><th><%= link_to "アカウント", user_path(section:"account", id: @user.id) %></th></tr>
                    </div>
                    <div>
                        <tr><th><%= link_to "プロフィール", user_path(section: "profile", id: @user.id) %></th></tr>
                    </div>
                <% else %>
                    <div>
                        <tr><th><%= link_to "アカウント", user_path(section:"account", id:@user.id) %></th></tr>
                    </div>
                    <div>
                        <tr class="orange"><th><%= link_to "プロフィール", user_path(section: "profile", id: @user.id) %></th></tr>
                    </div>
                <% end %>
            </table>
        </div>
        <div class="profile-data">
            <div class="table-name">
                <h3><%= obj0 %></h3>
            </div>
            <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
                <%= render "users/shared/error_messages", resource: resource %>
                <table class="table-type1 user-detail">            
                    <tr>
                        <th><%= User.human_attribute_name(obj1) %></th>
                        <% if obj1 == :icon %>
                            <td>
                                <div class="icon-edit">
                                    <%= image_tag @user[obj1] %>
                                    <div class="field">
                                        <%= f.file_field obj1, autofocus: true %>
                                    </div>
                                </div>
                            </td>
                        <% else %>
                            <td>
                                <div class="field">
                                    <%= f.text_field obj1, autofocus: true %>
                                </div>
                            </td>
                        <% end %>
                    </tr>
                    <% if obj2 == :password %>
                        <tr>
                            <th>
                                <%= User.human_attribute_name(obj2) %><br>
                                <p>変更する場合のみ入力(6文字以上)</p>
                            </th>
                            <td>
                                <div class="field">
                                    <%= f.password_field obj2, autofocus: true %>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <%= User.human_attribute_name(:password_confirmation) %><br>
                                <p>(パスワードを変更する場合は必須です)</p>
                            </th>
                            <td>
                                <div class="field">
                                    <%= f.password_field :password_confirmation, autofocus: true %>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <th>
                                <%= User.human_attribute_name(:current_password) %><br>
                                <p>(パスワードを変更する場合は必須です)</p>
                            </th>
                            <td>
                                <div class="field">
                                    <%= f.password_field :current_password, autofocus: true %>
                                </div>
                            </td>
                        </tr>
                    <% else %>
                        <tr>
                            <th>
                                <%= User.human_attribute_name(obj2) %><br>
                            </th>
                            <td>
                                <div class="field">
                                    <%= f.text_field obj2, autofocus: true %>
                                </div>
                            </td>
                        </tr>
                    <% end %>
                    <tr>
                        <% unless obj3 == "" %>
                            <th><%= User.human_attribute_name(obj3) %></th>
                        <% else %>
                            <th></th>
                        <% end %>
                        <div class="field">
                            <% unless obj3 == "" %>
                                <td><%= f.text_area obj3, autofocus: true %></td>
                            <% else %>
                                <td></td>
                            <% end %>
                            <% f.hidden_field :section, :value => @section %>                   
                        </div>
                    </tr>
                </table>                
                <div class="edit-buttons">
                    <%= link_to "キャンセル", :back %>
                    <div class="actions">
                        <%= f.submit "更新" %>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/shared/_area.html.erb
<div class="area">
    <%= image_tag pic %>
    <div class="area-content">
        <p><%= p1 %></p>
        <p><%= p2 %></p>
    </div>
</div>

app/views/shared/_footer.html.erb
<footer>
    <div class="container">
            <h2>Potepan Share</h2>
            <p>Copyright ©️Potepan Share 2023 All rights reserved</p>
    </div>
</footer>

app/views/shared/_header.html.erb
<header>
    <div class="container">
        <div class="logo">
            <%= link_to "Potepan Share", "/" %>
        </div>
        <% if user_signed_in? %>
            <div class="user-function">
                <div class="user-icon">
                    <%= image_tag current_user.icon %>
                    <p id="toggle"><%= current_user.name %><span class="close" id="button">▼</span></p>
                </div>
                <div class="user-menu">
                    <%= link_to "施設の新規登録", new_room_path %>
                    <%= link_to "予約済み一覧", reservations_path(id:current_user.id) %>
                    <%= link_to "登録済み一覧", "/rooms/own/#{current_user.id}" %>
                    <%= link_to "アカウント設定", user_path(id:current_user.id, section:"account") %>
                    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
                </div>
            </div>
        <% else %>
            <div class="header-functions">
                <%= link_to "新規登録", new_user_registration_path %>
                <%= link_to "ログイン", new_user_session_url %>
            </div>
        <% end %>
    </div>
</header>
<% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
<% end %>

app/views/shared/_room.html.erb
<div class="room-wrapper">
    <%= image_tag obj.icon %>
    <div class="room">
        <h4><%= obj.name %></h4>
        <p class="address"><%= obj.address %></p>
        <p class="detail"><%= obj.detail %></p>
        <p class="fee">¥<%= obj.fee %>〜</p>
        <%= link_to "詳細はこちら", obj %>
    </div>
</div>

app/views/shared/_search.html.erb
<div class="form-wrapper" >
    <div class="container">
        <%= form_with(url:rooms_path, method: :get, class: "search-field") do |f| %>
            <div class="field">
                <%= f.text_field :address, autofocus: true, placeholder: "エリア名を入力" %>
            </div>
            <div class="field">
                <%= f.text_field :keyword, autofocus: true, placeholder: "キーワードを入力" %>
            </div>
            <%= f.hidden_field :search, value: "2" %>
            <div class="actions">
                <%= f.submit "検索" %>
            </div>
        <% end %>
    </div>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li class="errors"><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
<% if @section == "account" %>
    <%= render "shared/account", obj0: "アカウント", obj1: :email, obj2: :password, obj3: "", section:@section %>
<% else %>
    <%= render "shared/account", obj0: "プロフィール", obj1: :icon, obj2: :name, obj3: :introduce, section:@section %>
<% end %>